// Full 249-country ISO list with alpha-2, alpha-3, name, and dial code
const countries = [
  { code2: "AF", code3: "AFG", name: "Afghanistan", dial: "+93" },
  { code2: "AL", code3: "ALB", name: "Albania", dial: "+355" },
  { code2: "DZ", code3: "DZA", name: "Algeria", dial: "+213" },
  { code2: "AS", code3: "ASM", name: "American Samoa", dial: "+1-684" },
  { code2: "AD", code3: "AND", name: "Andorra", dial: "+376" },
  { code2: "AO", code3: "AGO", name: "Angola", dial: "+244" },
  { code2: "AI", code3: "AIA", name: "Anguilla", dial: "+1-264" },
  { code2: "AQ", code3: "ATA", name: "Antarctica", dial: "+672" },
  { code2: "AG", code3: "ATG", name: "Antigua and Barbuda", dial: "+1-268" },
  { code2: "AR", code3: "ARG", name: "Argentina", dial: "+54" },
  { code2: "AM", code3: "ARM", name: "Armenia", dial: "+374" },
  { code2: "AW", code3: "ABW", name: "Aruba", dial: "+297" },
  { code2: "AU", code3: "AUS", name: "Australia", dial: "+61" },
  { code2: "AT", code3: "AUT", name: "Austria", dial: "+43" },
  { code2: "AZ", code3: "AZE", name: "Azerbaijan", dial: "+994" },
  { code2: "BS", code3: "BHS", name: "Bahamas", dial: "+1-242" },
  { code2: "BH", code3: "BHR", name: "Bahrain", dial: "+973" },
  { code2: "BD", code3: "BGD", name: "Bangladesh", dial: "+880" },
  { code2: "BB", code3: "BRB", name: "Barbados", dial: "+1-246" },
  { code2: "BY", code3: "BLR", name: "Belarus", dial: "+375" },
  { code2: "BE", code3: "BEL", name: "Belgium", dial: "+32" },
  { code2: "BZ", code3: "BLZ", name: "Belize", dial: "+501" },
  { code2: "BJ", code3: "BEN", name: "Benin", dial: "+229" },
  { code2: "BM", code3: "BMU", name: "Bermuda", dial: "+1-441" },
  { code2: "BT", code3: "BTN", name: "Bhutan", dial: "+975" },
  { code2: "BO", code3: "BOL", name: "Bolivia", dial: "+591" },
  { code2: "BA", code3: "BIH", name: "Bosnia and Herzegovina", dial: "+387" },
  { code2: "BW", code3: "BWA", name: "Botswana", dial: "+267" },
  { code2: "BR", code3: "BRA", name: "Brazil", dial: "+55" },
  { code2: "IO", code3: "IOT", name: "British Indian Ocean Territory", dial: "+246" },
  { code2: "VG", code3: "VGB", name: "British Virgin Islands", dial: "+1-284" },
  { code2: "BN", code3: "BRN", name: "Brunei Darussalam", dial: "+673" },
  { code2: "BG", code3: "BGR", name: "Bulgaria", dial: "+359" },
  { code2: "BF", code3: "BFA", name: "Burkina Faso", dial: "+226" },
  { code2: "BI", code3: "BDI", name: "Burundi", dial: "+257" },
  { code2: "KH", code3: "KHM", name: "Cambodia", dial: "+855" },
  { code2: "CM", code3: "CMR", name: "Cameroon", dial: "+237" },
  { code2: "CA", code3: "CAN", name: "Canada", dial: "+1" },
  { code2: "CV", code3: "CPV", name: "Cape Verde", dial: "+238" },
  { code2: "KY", code3: "CYM", name: "Cayman Islands", dial: "+1-345" },
  { code2: "CF", code3: "CAF", name: "Central African Republic", dial: "+236" },
  { code2: "TD", code3: "TCD", name: "Chad", dial: "+235" },
  { code2: "CL", code3: "CHL", name: "Chile", dial: "+56" },
  { code2: "CN", code3: "CHN", name: "China", dial: "+86" },
  { code2: "CX", code3: "CXR", name: "Christmas Island", dial: "+61" },
  { code2: "CC", code3: "CCK", name: "Cocos (Keeling) Islands", dial: "+61" },
  { code2: "CO", code3: "COL", name: "Colombia", dial: "+57" },
  { code2: "KM", code3: "COM", name: "Comoros", dial: "+269" },
  { code2: "CK", code3: "COK", name: "Cook Islands", dial: "+682" },
  { code2: "CR", code3: "CRI", name: "Costa Rica", dial: "+506" },
  { code2: "HR", code3: "HRV", name: "Croatia", dial: "+385" },
  { code2: "CU", code3: "CUB", name: "Cuba", dial: "+53" },
  { code2: "CW", code3: "CUW", name: "Curacao", dial: "+599" },
  { code2: "CY", code3: "CYP", name: "Cyprus", dial: "+357" },
  { code2: "CZ", code3: "CZE", name: "Czech Republic", dial: "+420" },
  { code2: "CD", code3: "COD", name: "Democratic Republic of the Congo", dial: "+243" },
  { code2: "DK", code3: "DNK", name: "Denmark", dial: "+45" },
  { code2: "DJ", code3: "DJI", name: "Djibouti", dial: "+253" },
  { code2: "DM", code3: "DMA", name: "Dominica", dial: "+1-767" },
  { code2: "DO", code3: "DOM", name: "Dominican Republic", dial: "+1-809" },
  { code2: "EC", code3: "ECU", name: "Ecuador", dial: "+593" },
  { code2: "EG", code3: "EGY", name: "Egypt", dial: "+20" },
  { code2: "SV", code3: "SLV", name: "El Salvador", dial: "+503" },
  { code2: "GQ", code3: "GNQ", name: "Equatorial Guinea", dial: "+240" },
  { code2: "ER", code3: "ERI", name: "Eritrea", dial: "+291" },
  { code2: "EE", code3: "EST", name: "Estonia", dial: "+372" },
  { code2: "ET", code3: "ETH", name: "Ethiopia", dial: "+251" },
  { code2: "FK", code3: "FLK", name: "Falkland Islands", dial: "+500" },
  { code2: "FO", code3: "FRO", name: "Faroe Islands", dial: "+298" },
  { code2: "FJ", code3: "FJI", name: "Fiji", dial: "+679" },
  { code2: "FI", code3: "FIN", name: "Finland", dial: "+358" },
  { code2: "FR", code3: "FRA", name: "France", dial: "+33" },
  { code2: "GF", code3: "GUF", name: "French Guiana", dial: "+594" },
  { code2: "PF", code3: "PYF", name: "French Polynesia", dial: "+689" },
  { code2: "GA", code3: "GAB", name: "Gabon", dial: "+241" },
  { code2: "GM", code3: "GMB", name: "Gambia", dial: "+220" },
  { code2: "GE", code3: "GEO", name: "Georgia", dial: "+995" },
  { code2: "DE", code3: "DEU", name: "Germany", dial: "+49" },
  { code2: "GH", code3: "GHA", name: "Ghana", dial: "+233" },
  { code2: "GI", code3: "GIB", name: "Gibraltar", dial: "+350" },
  { code2: "GR", code3: "GRC", name: "Greece", dial: "+30" },
  { code2: "GL", code3: "GRL", name: "Greenland", dial: "+299" },
  { code2: "GD", code3: "GRD", name: "Grenada", dial: "+1-473" },
  { code2: "GP", code3: "GLP", name: "Guadeloupe", dial: "+590" },
  { code2: "GU", code3: "GUM", name: "Guam", dial: "+1-671" },
  { code2: "GT", code3: "GTM", name: "Guatemala", dial: "+502" },
  { code2: "GG", code3: "GGY", name: "Guernsey", dial: "+44-1481" },
  { code2: "GN", code3: "GIN", name: "Guinea", dial: "+224" },
  { code2: "GW", code3: "GNB", name: "Guinea-Bissau", dial: "+245" },
  { code2: "GY", code3: "GUY", name: "Guyana", dial: "+592" },
  { code2: "HT", code3: "HTI", name: "Haiti", dial: "+509" },
  { code2: "HN", code3: "HND", name: "Honduras", dial: "+504" },
  { code2: "HK", code3: "HKG", name: "Hong Kong", dial: "+852" },
  { code2: "HU", code3: "HUN", name: "Hungary", dial: "+36" },
  { code2: "IS", code3: "ISL", name: "Iceland", dial: "+354" },
  { code2: "IN", code3: "IND", name: "India", dial: "+91" },
  { code2: "ID", code3: "IDN", name: "Indonesia", dial: "+62" },
  { code2: "IR", code3: "IRN", name: "Iran", dial: "+98" },
  { code2: "IQ", code3: "IRQ", name: "Iraq", dial: "+964" },
  { code2: "IE", code3: "IRL", name: "Ireland", dial: "+353" },
  { code2: "IM", code3: "IMN", name: "Isle of Man", dial: "+44-1624" },
  { code2: "IL", code3: "ISR", name: "Israel", dial: "+972" },
  { code2: "IT", code3: "ITA", name: "Italy", dial: "+39" },
  { code2: "CI", code3: "CIV", name: "Ivory Coast", dial: "+225" },
  { code2: "JM", code3: "JAM", name: "Jamaica", dial: "+1-876" },
  { code2: "JP", code3: "JPN", name: "Japan", dial: "+81" },
  { code2: "JE", code3: "JEY", name: "Jersey", dial: "+44-1534" },
  { code2: "JO", code3: "JOR", name: "Jordan", dial: "+962" },
  { code2: "KZ", code3: "KAZ", name: "Kazakhstan", dial: "+7" },
  { code2: "KE", code3: "KEN", name: "Kenya", dial: "+254" },
  { code2: "KI", code3: "KIR", name: "Kiribati", dial: "+686" },
  { code2: "KW", code3: "KWT", name: "Kuwait", dial: "+965" },
  { code2: "KG", code3: "KGZ", name: "Kyrgyzstan", dial: "+996" },
  { code2: "LA", code3: "LAO", name: "Laos", dial: "+856" },
  { code2: "LV", code3: "LVA", name: "Latvia", dial: "+371" },
  { code2: "LB", code3: "LBN", name: "Lebanon", dial: "+961" },
  { code2: "LS", code3: "LSO", name: "Lesotho", dial: "+266" },
  { code2: "LR", code3: "LBR", name: "Liberia", dial: "+231" },
  { code2: "LY", code3: "LBY", name: "Libya", dial: "+218" },
  { code2: "LI", code3: "LIE", name: "Liechtenstein", dial: "+423" },
  { code2: "LT", code3: "LTU", name: "Lithuania", dial: "+370" },
  { code2: "LU", code3: "LUX", name: "Luxembourg", dial: "+352" },
  { code2: "MO", code3: "MAC", name: "Macao", dial: "+853" },
  { code2: "MG", code3: "MDG", name: "Madagascar", dial: "+261" },
  { code2: "MW", code3: "MWI", name: "Malawi", dial: "+265" },
  { code2: "MY", code3: "MYS", name: "Malaysia", dial: "+60" },
  { code2: "MV", code3: "MDV", name: "Maldives", dial: "+960" },
  { code2: "ML", code3: "MLI", name: "Mali", dial: "+223" },
  { code2: "MT", code3: "MLT", name: "Malta", dial: "+356" },
  { code2: "MH", code3: "MHL", name: "Marshall Islands", dial: "+692" },
  { code2: "MQ", code3: "MTQ", name: "Martinique", dial: "+596" },
  { code2: "MR", code3: "MRT", name: "Mauritania", dial: "+222" },
  { code2: "MU", code3: "MUS", name: "Mauritius", dial: "+230" },
  { code2: "YT", code3: "MYT", name: "Mayotte", dial: "+262" },
  { code2: "MX", code3: "MEX", name: "Mexico", dial: "+52" },
  { code2: "FM", code3: "FSM", name: "Micronesia", dial: "+691" },
  { code2: "MD", code3: "MDA", name: "Moldova", dial: "+373" },
  { code2: "MC", code3: "MCO", name: "Monaco", dial: "+377" },
  { code2: "MN", code3: "MNG", name: "Mongolia", dial: "+976" },
  { code2: "ME", code3: "MNE", name: "Montenegro", dial: "+382" },
  { code2: "MS", code3: "MSR", name: "Montserrat", dial: "+1-664" },
  { code2: "MA", code3: "MAR", name: "Morocco", dial: "+212" },
  { code2: "MZ", code3: "MOZ", name: "Mozambique", dial: "+258" },
  { code2: "MM", code3: "MMR", name: "Myanmar", dial: "+95" },
  { code2: "NA", code3: "NAM", name: "Namibia", dial: "+264" },
  { code2: "NR", code3: "NRU", name: "Nauru", dial: "+674" },
  { code2: "NP", code3: "NPL", name: "Nepal", dial: "+977" },
  { code2: "NL", code3: "NLD", name: "Netherlands", dial: "+31" },
  { code2: "NC", code3: "NCL", name: "New Caledonia", dial: "+687" },
  { code2: "NZ", code3: "NZL", name: "New Zealand", dial: "+64" },
  { code2: "NI", code3: "NIC", name: "Nicaragua", dial: "+505" },
  { code2: "NE", code3: "NER", name: "Niger", dial: "+227" },
  { code2: "NG", code3: "NGA", name: "Nigeria", dial: "+234" },
  { code2: "NU", code3: "NIU", name: "Niue", dial: "+683" },
  { code2: "NF", code3: "NFK", name: "Norfolk Island", dial: "+672" },
  { code2: "KP", code3: "PRK", name: "North Korea", dial: "+850" },
  { code2: "MK", code3: "MKD", name: "North Macedonia", dial: "+389" },
  { code2: "MP", code3: "MNP", name: "Northern Mariana Islands", dial: "+1-670" },
  { code2: "NO", code3: "NOR", name: "Norway", dial: "+47" },
  { code2: "OM", code3: "OMN", name: "Oman", dial: "+968" },
  { code2: "PK", code3: "PAK", name: "Pakistan", dial: "+92" },
  { code2: "PW", code3: "PLW", name: "Palau", dial: "+680" },
  { code2: "PS", code3: "PSE", name: "Palestine", dial: "+970" },
  { code2: "PA", code3: "PAN", name: "Panama", dial: "+507" },
  { code2: "PG", code3: "PNG", name: "Papua New Guinea", dial: "+675" },
  { code2: "PY", code3: "PRY", name: "Paraguay", dial: "+595" },
  { code2: "PE", code3: "PER", name: "Peru", dial: "+51" },
  { code2: "PH", code3: "PHL", name: "Philippines", dial: "+63" },
  { code2: "PL", code3: "POL", name: "Poland", dial: "+48" },
  { code2: "PT", code3: "PRT", name: "Portugal", dial: "+351" },
  { code2: "PR", code3: "PRI", name: "Puerto Rico", dial: "+1-787" },
  { code2: "QA", code3: "QAT", name: "Qatar", dial: "+974" },
  { code2: "CG", code3: "COG", name: "Republic of the Congo", dial: "+242" },
  { code2: "RE", code3: "REU", name: "Reunion", dial: "+262" },
  { code2: "RO", code3: "ROU", name: "Romania", dial: "+40" },
  { code2: "RU", code3: "RUS", name: "Russia", dial: "+7" },
  { code2: "RW", code3: "RWA", name: "Rwanda", dial: "+250" },
  { code2: "BL", code3: "BLM", name: "Saint Barthelemy", dial: "+590" },
  { code2: "SH", code3: "SHN", name: "Saint Helena", dial: "+290" },
  { code2: "KN", code3: "KNA", name: "Saint Kitts and Nevis", dial: "+1-869" },
  { code2: "LC", code3: "LCA", name: "Saint Lucia", dial: "+1-758" },
  { code2: "MF", code3: "MAF", name: "Saint Martin", dial: "+590" },
  { code2: "PM", code3: "SPM", name: "Saint Pierre and Miquelon", dial: "+508" },
  { code2: "VC", code3: "VCT", name: "Saint Vincent and the Grenadines", dial: "+1-784" },
  { code2: "WS", code3: "WSM", name: "Samoa", dial: "+685" },
  { code2: "SM", code3: "SMR", name: "San Marino", dial: "+378" },
  { code2: "ST", code3: "STP", name: "Sao Tome and Principe", dial: "+239" },
  { code2: "SA", code3: "SAU", name: "Saudi Arabia", dial: "+966" },
  { code2: "SN", code3: "SEN", name: "Senegal", dial: "+221" },
  { code2: "RS", code3: "SRB", name: "Serbia", dial: "+381" },
  { code2: "SC", code3: "SYC", name: "Seychelles", dial: "+248" },
  { code2: "SL", code3: "SLE", name: "Sierra Leone", dial: "+232" },
  { code2: "SG", code3: "SGP", name: "Singapore", dial: "+65" },
  { code2: "SX", code3: "SXM", name: "Sint Maarten", dial: "+1-721" },
  { code2: "SK", code3: "SVK", name: "Slovakia", dial: "+421" },
  { code2: "SI", code3: "SVN", name: "Slovenia", dial: "+386" },
  { code2: "SB", code3: "SLB", name: "Solomon Islands", dial: "+677" },
  { code2: "SO", code3: "SOM", name: "Somalia", dial: "+252" },
  { code2: "ZA", code3: "ZAF", name: "South Africa", dial: "+27" },
  { code2: "KR", code3: "KOR", name: "South Korea", dial: "+82" },
  { code2: "SS", code3: "SSD", name: "South Sudan", dial: "+211" },
  { code2: "ES", code3: "ESP", name: "Spain", dial: "+34" },
  { code2: "LK", code3: "LKA", name: "Sri Lanka", dial: "+94" },
  { code2: "SD", code3: "SDN", name: "Sudan", dial: "+249" },
  { code2: "SR", code3: "SUR", name: "Suriname", dial: "+597" },
  { code2: "SJ", code3: "SJM", name: "Svalbard and Jan Mayen", dial: "+47" },
  { code2: "SE", code3: "SWE", name: "Sweden", dial: "+46" },
  { code2: "CH", code3: "CHE", name: "Switzerland", dial: "+41" },
  { code2: "SY", code3: "SYR", name: "Syria", dial: "+963" },
  { code2: "TW", code3: "TWN", name: "Taiwan", dial: "+886" },
  { code2: "TJ", code3: "TJK", name: "Tajikistan", dial: "+992" },
  { code2: "TZ", code3: "TZA", name: "Tanzania", dial: "+255" },
  { code2: "TH", code3: "THA", name: "Thailand", dial: "+66" },
  { code2: "TL", code3: "TLS", name: "Timor-Leste", dial: "+670" },
  { code2: "TG", code3: "TGO", name: "Togo", dial: "+228" },
  { code2: "TK", code3: "TKL", name: "Tokelau", dial: "+690" },
  { code2: "TO", code3: "TON", name: "Tonga", dial: "+676" },
  { code2: "TT", code3: "TTO", name: "Trinidad and Tobago", dial: "+1-868" },
  { code2: "TN", code3: "TUN", name: "Tunisia", dial: "+216" },
  { code2: "TR", code3: "TUR", name: "Turkey", dial: "+90" },
  { code2: "TM", code3: "TKM", name: "Turkmenistan", dial: "+993" },
  { code2: "TC", code3: "TCA", name: "Turks and Caicos Islands", dial: "+1-649" },
  { code2: "TV", code3: "TUV", name: "Tuvalu", dial: "+688" },
  { code2: "UG", code3: "UGA", name: "Uganda", dial: "+256" },
  { code2: "UA", code3: "UKR", name: "Ukraine", dial: "+380" },
  { code2: "AE", code3: "ARE", name: "United Arab Emirates", dial: "+971" },
  { code2: "GB", code3: "GBR", name: "United Kingdom", dial: "+44" },
  { code2: "US", code3: "USA", name: "United States", dial: "+1" },
  { code2: "UY", code3: "URY", name: "Uruguay", dial: "+598" },
  { code2: "UZ", code3: "UZB", name: "Uzbekistan", dial: "+998" },
  { code2: "VU", code3: "VUT", name: "Vanuatu", dial: "+678" },
  { code2: "VA", code3: "VAT", name: "Vatican City", dial: "+379" },
  { code2: "VE", code3: "VEN", name: "Venezuela", dial: "+58" },
  { code2: "VN", code3: "VNM", name: "Vietnam", dial: "+84" },
  { code2: "WF", code3: "WLF", name: "Wallis and Futuna", dial: "+681" },
  { code2: "EH", code3: "ESH", name: "Western Sahara", dial: "+212" },
  { code2: "YE", code3: "YEM", name: "Yemen", dial: "+967" },
  { code2: "ZM", code3: "ZMB", name: "Zambia", dial: "+260" },
  { code2: "ZW", code3: "ZWE", name: "Zimbabwe", dial: "+263" }
];

export default countries;
